# ----------------- 逻辑库名 -----------------
databaseName: ds0 # 逻辑库名，可映射到物理库
dataSources:
  ds0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/order0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
    username: root
    password: '123456'
# ===================== 分片规则配置 =====================
rules:
  - !SHARDING
    tables:
      t_order:
        actualDataNodes: ds0.t_order_$->{0..3}
        tableStrategy:
          standard:
            shardingColumn: order_id
            shardingAlgorithmName: order_inline
        keyGenerateStrategy: # 主键生成策略
          column: id
          keyGeneratorName: snowflake
    keyGenerators:
      # 此处必须要配置，否则会导致报错，因为shardingsphere-jdbc-core-spring-boot-starter需要加载此项配置，官网的demo例子有错
      snowflake:
        type: SNOWFLAKE
        props:
          worker-id: 123
    shardingAlgorithms:
      order_inline:
        type: INLINE
        props:
          algorithm-expression: t_order_$->{order_id % 4}
# ===================== 全局属性 =====================
props:
  sql-show: true   # 控制台打印 SQL